apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-boostrap 
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: .
    repoURL: https://github.com/pbmoses/vanilla-gitops
    targetRevision: HEAD
  syncPolicy: {}

